
default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: beowulf_dev
  username: <%= ENV['DEV_DB_USER'] %>
  password: <%= ENV['DEV_DB_PASSWORD'] %>
  host: localhost

test:
  <<: *default
  database: beowulf_test
  username: <%= ENV['TEST_DB_USER'] %>
  password: <%= ENV['TEST_DB_PASSWORD'] %>
  host: localhost

production:
  <<: *default
  database: beowulf_prod
  username: <%= ENV['PROD_DB_USER'] %>
  password: <%= ENV['PROD_DB_PASSWORD'] %>
  host: localhost